### ISSUE TITLE
DisallowedLooseComparisonRule should exclude DateTime(Immutable)

### ISSUE THREAD

**Issue by karstennilsen** [phpstan/phpstan-strict-rules#252] opened 2024-11-28 20:37 UTC
```php
(new \DateTimeImmutable('2024-05-02 00:00:00')) === (new \DateTimeImmutable('2024-05-02 00:00:00'))
// returns false
```

Strict comparison makes not a lot of sense for DateTime objects in PHP. I like the rest to be strict in comparison, but not this.

**Comment by ondrejmirtes** [comment] 2024-11-28 20:51
Duplicate of https://github.com/phpstan/phpstan-strict-rules/issues/232

**Closed as completed by ondrejmirtes** 2024-11-28 20:51 UTC
