### ISSUE TITLE
Bleeding edge + strict rules in v1.12.11 suggests comparing DateTime objects via strict comparison.

### ISSUE THREAD

**Issue by whataboutpereira** [phpstan/phpstan-strict-rules#251] opened 2024-11-19 15:21 UTC
### Bug report

Dates in DateTime objects can be compared only using the loose == operator, however when I switched bleeding edge on (on top of strict rules), phpstan started suggesting to compare DateTime objects via strict === comparison, which compares the objects themselves, instead of dates.

### Code snippet that reproduces the problem

https://phpstan.org/r/2c276792-c7f0-41b1-bde7-2dc8de08adcb

### Expected output

I think phpstan should not suggest strict comparison using === for DateTime and other date objects.

**Comment by janedbal** [comment] 2024-11-19 20:43
Just FYI there are custom rules to deny the strict comparison: https://github.com/shipmonk-rnd/phpstan-rules?tab=readme-ov-file#forbididenticalclasscomparison

**Comment by whataboutpereira** [comment] 2024-11-25 14:24
Oh, somehow I missed the existing https://github.com/phpstan/phpstan-strict-rules/issues/232

**Comment by ondrejmirtes** [comment] 2024-11-25 16:10
Duplicate of https://github.com/phpstan/phpstan-strict-rules/issues/232

**Closed as completed by ondrejmirtes** 2024-11-25 16:10 UTC
