### ISSUE TITLE
Incorrect generics on Iterator

### ISSUE THREAD

**Issue by nusje2000** [phpstan/phpstan-strict-rules#155] opened 2022-01-19 16:29 UTC
https://phpstan.org/r/642defe4-682f-4216-b8c7-6c36a9dfff67

When using the `current` function on an Iterator, the return should be `T|null` since null is returned when the iterator is empty.

**Comment by ondrejmirtes** [comment] 2022-01-20 09:02
Duplicate of https://github.com/phpstan/phpstan/issues/3674

**Closed by ondrejmirtes** 2022-01-20 09:02 UTC
